### ISSUE TITLE
Add JLine

### ISSUE THREAD

**Issue by ngocdaothanh** [xitrum-framework/scalive#1]
* Arrows
* Allow pasting block of code

https://github.com/jline/jline2
https://www.assembla.com/code/scala-eclipse-toolchain/git/nodes/master/src/jline/src/test/java/scala/tools/jline/example/Example.java

Related tool:
https://github.com/woshilaiceshide/scala-web-repl

**Comment by eallik** [comment]
I tried looking into why arrow keys don't work; with pure Scala code, line history and navigation works perfectly fine out of the box, but playing with the Java code in `Repl.java` didn't have any effect on how the REPL behaved in terms of line history.

Any insight there?

**Comment by ngocdaothanh** [comment]
For now, I'll try to merge Oshida's #4 pull request. It provides arrow keys.

It has problem that causes problem to your console keys after the Scalive REPL exits, but that's still a good tradeoff.

**Comment by ngocdaothanh** [comment]
@georgeOsdDev 

In your PR, you added JLine to the client.
I think maybe we can add JLine to the server.
Maybe that will allow us to have console navigation (using arrow keys etc.) and autocomplete.

I'll investigate that approach.

**Comment by ngocdaothanh** [comment]
@georgeOsdDev 

I've finished this based on your code.
I could use your code as-is, because it's not totally correct:
The code starts a REPL on the client side.

**Comment by ngocdaothanh** [comment]
v1.6 with this feature has been released:
https://github.com/xitrum-framework/scalive/releases/tag/1.6

**Comment by georgeOsdDev** [comment]
🎉
