### ISSUE TITLE
scalive hijacks Play's stdout console

### ISSUE THREAD

**Issue by shanness** [xitrum-framework/scalive#21]
Hi,

When I connect to play, plays console output stops displaying, and it starts displaying in scalive instead.
Is there any way to stop this, and just have my own output shown?

Basically our server is always logging stuff, so makes this REPL unusable.

Thanks.  Looking forward to trying it properly, looks great!  
Been using this, but really miss tab completion, so interested in yours.

Sorry if I'm missing something obvious.

https://github.com/nraychaudhuri/scala-remote-repl

```
scalive-1.6$ ./scalive `./scalive  | grep ProdSer | awk '{print $1}'`
[Scalive] Attach to target process at port 60839
[warn] c.AbstractCalendarService - NO TIMEZONE for event[qbe4f4eumbs9j2lobkudhhl4f8]
Welcome to Scala 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_121).
Type in expressions for evaluation. Or try :help.

scala> [debug] maps.GoogleMaps - Google geocoder returned 1 results.
[info] models.Geocode - Initialised Geocode : 1/18 Warraba St Hurstville: -33.9521309, 
```

**Comment by shanness** [comment]
BTW, in plays console, I get this
```
[info] scalive.Log - [Scalive] Open local port 44840 for REPL and completer
[info] scalive.Log - [Scalive] REPL connected
[info] scalive.Log - [Scalive] Completer connected
[info] scalive.Log - [Scalive] Load /home/ubookr/apps/scalive-1.6/scalive-1.6.jar
[Scalive] REPL closed
[info] scalive.Log - [Scalive] Completer closed
```

And until it's closed, no other output (all goes to scalive)

**Comment by ngocdaothanh** [comment]
> And until it's closed, no other output (all goes to scalive)

Yes, it's the intentional behavior, not a bug.
